using System;
using System.Collections.Generic;
using System.Text;

namespace BlaBlaCarAz.Localization
{
   public class SharedResource
    {
        public static string Document { get; set; }
        public static string Bag { get; set; }
        public static string Search { get; set; }
        public static string From { get; set; }
        public static string To { get; set; }
        public static string YourRide { get; set; }
        public static string HomePage { get; set; }
        public static string Limits { get; set; }
        public static string Language { get; set; }
        public static string FindRide { get; set; }
        public static string OfferRide { get; set; }
        public static string Register { get; set; }
        public static string Login { get; set; }
        public static string Login1 { get; set; }
        public static string LoginHeader { get; set; }
        public static string Email { get; set; }
        public static string Password { get; set; }
        public static string RememberMe { get; set; }
        public static string ForgotPassword { get; set; }
        public static string RegisterAsNewUser { get; set; }
        public static string LoginHeader2 { get; set; }
        public static string Privacy { get; set; }
        public static string EmailRequired { get; set; }
        public static string PasswordRequired { get; set; }
        public static string CreateNewAccount { get; set; }
        public static string PhoneNumber { get; set; }
        public static string NameLastName { get; set; }
        public static string BirthDate { get; set; }
        public static string ConfirmPassword { get; set; }
        public static string PhoneNumberRequired { get; set; }
        public static string PasswordLength { get; set; }
        public static string PasswordCompare { get; set; }
        public static string NameLastNameRequired { get; set; }
        public static string RegisterConfirmation { get; set; }
        public static string CheckEmailForAccountConfirm { get; set; }
        public static string ConfirmEmail { get; set; }
        public static string ConfirmEmailBody { get; set; }
        public static string Profile { get; set; }
        public static string YourRides { get; set; }
        public static string Payments { get; set; }
        public static string BookRequests { get; set; }
        public static string Messages { get; set; }
        public static string Logout { get; set; }
        public static string PaymentsAndRefunds { get; set; }
        public static string PaymentsAndRefundsHeader2 { get; set; }
        public static string When { get; set; }
        public static string AppUser { get; set; }
        public static string BookingDate { get; set; }
        public static string ConfirmStatus { get; set; }
        public static string LoadLimits { get; set; }
        public static string Delete { get; set; }
        public static string WhereWantGo { get; set; }
        public static string RidesAvailable { get; set; }
        public static string RideAvailable { get; set; }
        public static string NoRidesYet { get; set; }
        public static string Price { get; set; }
        public static string Continue { get; set; }
        public static string Send { get; set; }
        public static string Subject { get; set; }
        public static string PublicProfileHeader { get; set; }
        public static string PublicProfilePicture { get; set; }
        public static string Age { get; set; }
        public static string MemberSince { get; set; }
        public static string RidesPublished { get; set; }
        public static string ApprovalTitle { get; set; }
        public static string ApprovalHeader { get; set; }
        public static string YesSure { get; set; }
        public static string NoIReplyEachMyself { get; set; }
        public static string Arrival { get; set; }
        public static string WhereAreYouHeading { get; set; }
        public static string BookConfirmations { get; set; }
        public static string BookConfirmationsHeader1 { get; set; }
        public static string BookConfirmationsHeader2 { get; set; }
        public static string Confirm { get; set; }
        public static string CommentHeader { get; set; }
        public static string Comment { get; set; }
        public static string CommentPlaceholder { get; set; }
        public static string Departure { get; set; }
        public static string DepartureHeader { get; set; }
        public static string DepartureDate { get; set; }
        public static string DepartureDateHeader { get; set; }
        public static string DepartureFlightNumber { get; set; }
        public static string DepartureFlightNumberHeader { get; set; }
        public static string DepartureTime { get; set; }
        public static string DepartureTimeHeader { get; set; }
        public static string LoadType { get; set; }
        public static string PriceRecommendation { get; set; }
        public static string PriceRecommendationHeader { get; set; }
        public static string YesPerfect { get; set; }
        public static string NoINeedEditAmount { get; set; }
        public static string PriceSettingTitle { get; set; }
        public static string PriceSettingHeader { get; set; }
        public static string ProfilePictureTitle { get; set; }
        public static string ProfilePictureHeader { get; set; }
        public static string ChoosePicture { get; set; }
        public static string ProfilePictureChoiceTitle { get; set; }
        public static string ProfilePictureChoiceHeader { get; set; }
        public static string NoThanks { get; set; }
        public static string PublishRide { get; set; }
        public static string RidesHeader { get; set; }
        public static string TotalPrice { get; set; }
        public static string Contact { get; set; }
        public static string Passengers { get; set; }
        public static string Book { get; set; }
        public static string Username { get; set; }
        public static string RidePublished { get; set; }
        public static string NoRidesPublishedYet { get; set; }
        public static string ConfirmBookRequestEmailSubject { get; set; }
        public static string ConfirmBookRequestEmailBody { get; set; }
        public static string PaymentConfirmationEmailSubject { get; set; }
        public static string PaymentConfirmationEmailBody { get; set; }

    }
}
